name 'webserver'
maintainer 'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license 'all_rights'
description 'Installs/Configures webserver'
long_description 'Installs/Configures webserver'
version '0.1.0'
depends 'iis', '~> 4.1.1'
depends 'windows_firewall', '~> 3.0.0'
